# Generated by Django 5.2 on 2025-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('Mechanical Engineering', 'Mechanical Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Information Science and Engineering', 'Information Science and Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='semester',
            field=models.CharField(blank=True, choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Mechanical Engineering', 'Mechanical Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Information Science and Engineering', 'Information Science and Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering')], default='Information Science and Engineering', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8')], default='Semester 1', max_length=20),
            preserve_default=False,
        ),
    ]
